"""new fields in user model

Revision ID: 186ec849d040
Revises: 248f01f8e8f1
Create Date: 2021-05-31 16:17:50.160318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186ec849d040'
down_revision = '248f01f8e8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
